### ISSUE TITLE
COW-GNO pair is not visible in the pairs page

### ISSUE THREAD

**Issue by 0xVenky** [SwaprDAO/swapr-info#66]
This can be searched with the pair address though.

**Comment by guerrap** [comment]
The pair is visible on the last page. If this issue was referring to this I think we can close it.

![image](https://user-images.githubusercontent.com/9011637/169593381-66c23380-27ae-46fc-bf0a-f6f76d1c286e.png)

**Comment by guerrap** [comment]
Should we close this? @0xVenky

**Comment by guerrap** [comment]
After looking a bit more in-depth, right now the component fetches by default the first 100 tokens (sorted by liquidity), and since the `cow/gno` pair is not in the top 100, it's not displayed in the list. 
I also noticed that when you search and select the `cow/gno` pair from the search bar, the pair gets added to the list, because the state context Is the same.

Should we increase the top pairs limit to 200 (just like the tokens page)?

**Comment by 0xVenky** [comment]
> After looking a bit more in-depth, right now the component fetches by default the first 100 tokens (sorted by liquidity), and since the `cow/gno` pair is not in the top 100, it's not displayed in the list. I also noticed that when you search and select the `cow/gno` pair from the search bar, the pair gets added to the list, because the state context Is the same.
> 
> Should we increase the top pairs limit to 200 (just like the tokens page)?

MAkes sense for now. Lets increase to 200 for now until we have pagination later.
